### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ddo** [ddo/go-dlog#2]
- [x] error
- [x] pattern conditional output
- [ ] shortcut
- [x] move getDelta to delta.go
- [x] recheck append line
- [x] README installation revise
